export { createRegistry, FormatRegistry } from "./core/registry";
export { RetroImageError } from "./core/errors";
export { indexedToRgba, nearestColorIndex } from "./core/color";
export {
  analyzeDimensions,
  analyzePaletteCapabilities,
  genericConvert,
  isRgbOnComponentGrid,
  mapToPalette,
  medianCut,
  prepareConversionImage,
  quantizeRgbToComponentGrid,
  resolveRgbComponentPrecision
} from "./core/conversion";
export type {
  AnalysisIssue,
  AnalysisResult,
  AmigaPlanarDecodeOptions,
  AmigaPlanarEncodeOptions,
  AmigaPlanarLayout,
  BaseImageDocument,
  BinarySource,
  CharsetDocument,
  CodecTarget,
  CodecWarning,
  ConversionOptions,
  ConversionReport,
  ConversionResult,
  DecodeHints,
  DecodeOptions,
  DetectionResult,
  DimensionRange,
  DisplayVariantDefinition,
  DisplayProfile,
  DitherMode,
  EncodeOptions,
  EncodeResult,
  EncodingVariantDefinition,
  FormatDefinition,
  FormatModeDefinition,
  FormatPlugin,
  FloatSampledRasterDocument,
  IntegerSampledRasterDocument,
  JsonValue,
  ModeDimensions,
  InterlaceSupport,
  PaletteCapability,
  PaletteModel,
  PfmByteOrder,
  PfmDecodeOptions,
  PfmEncodeOptions,
  PfmRowOrder,
  PfmToneMapping,
  PreservedSection,
  ProbeContext,
  RasterDocument,
  Rational,
  ResourceLimits,
  RetroImageDocument,
  RgbColor,
  RgbComponentPrecision,
  RgbComponentPrecisionVariant,
  RgbaImage,
  SampleChannelModel,
  SampleCapability,
  SampledRasterDocument,
  ResolutionClass,
  StructuredPaletteRegisterDefinition,
  StructuredPaletteValueModel,
  TilemapDocument
} from "./core/types";
export type { RetroImageErrorCode } from "./core/errors";
